name: Build master

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet: [3.0.100]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Docker build
      run: |
        docker build -t ancestors-map .
        docker create -ti --name dummy ancestors-map bash
        docker cp dummy:/build/src/Client/deploy .
        docker rm -f dummy
    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: deploy
